In [1]:
import pandas as pd

In [94]:
#LOAD DATA
df1 = pd.read_excel(r'D:\KULIAH\Project\womanguard-index-surabaya\DATA BARU\X7 (Tingkat Literasi Digital Perempuan)\2025\Pendidikan 2025 semester1.xlsx')
df2 = pd.read_excel(r'D:\KULIAH\Project\womanguard-index-surabaya\DATA BARU\X7 (Tingkat Literasi Digital Perempuan)\2025\Pendidikan 2025 semester2.xlsx')

In [95]:
#DROP 4 kolom pertama
df1 = df1.iloc[3:].reset_index(drop=True)
df2 = df2.iloc[3:].reset_index(drop=True)

In [96]:
#Mengubah baris pertama jadi header
header_row1 = df1.iloc[0]
df1 = df1.iloc[1:].reset_index(drop=True).copy()
df1.columns = header_row1.values
df1.columns = df1.columns.str.replace("'", "", regex=False)

header_row2 = df2.iloc[0]
df2 = df2.iloc[1:].reset_index(drop=True).copy()
df2.columns = header_row2.values
df2.columns = df2.columns.str.replace("'", "", regex=False)

In [ ]:
#Ambil kecamatan aja
df1 = df1[df1['KECAMATAN/KELURAHAN'] == 'KECAMATAN']
df2 = df2[df2['KECAMATAN/KELURAHAN'] == 'KECAMATAN']

,KECAMATAN/KELURAHAN,WILAYAH,TIDAK/BELUM SEKOLAH_L,TIDAK/BELUM SEKOLAH_P,BELUM TAMAT SD/SEDERAJAT_L,BELUM TAMAT SD/SEDERAJAT_P,TAMAT SD/SEDERAJAT_L,TAMAT SD/SEDERAJAT_P,SLTP/SEDERAJAT_L,SLTP/SEDERAJAT_P,...,DIPLOMA I/II_L,DIPLOMA I/II_P,AKADEMI/DIPLOMA III/S.MUDA_L,AKADEMI/DIPLOMA III/S.MUDA_P,DIPLOMA IV/STRATA I_L,DIPLOMA IV/STRATA I_P,STRATA II_L,STRATA II_P,STRATA III_L,STRATA III_P
1,KECAMATAN,KARANG PILANG,103,79,142,132,1802,1339,2274,854,...,274,78,509,133,4045,750,352,64,27,8
6,KECAMATAN,WONOCOLO,129,103,210,108,2080,1411,2386,1039,...,253,93,556,159,4819,962,505,108,59,8
12,KECAMATAN,RUNGKUT,115,75,209,114,2562,1648,3241,1254,...,370,131,1037,244,9597,1785,1097,203,143,29
19,KECAMATAN,WONOKROMO,319,245,301,130,3848,3423,4454,2559,...,458,148,816,246,7162,1731,470,116,31,9
26,KECAMATAN,TEGALSARI,122,127,235,173,2792,2230,3189,1786,...,187,53,543,155,3170,834,206,39,19,2
32,KECAMATAN,SAWAHAN,1103,582,449,168,7580,5533,7505,3601,...,273,67,820,232,6155,1383,415,116,30,2
39,KECAMATAN,GENTENG,101,103,144,134,2179,1619,2126,1152,...,101,39,229,103,2199,643,141,34,17,1
45,KECAMATAN,GUBENG,191,205,244,124,3021,2484,3589,1977,...,220,72,1039,384,8124,2111,684,143,67,9
52,KECAMATAN,SUKOLILO,349,201,229,108,3675,2060,3464,1283,...,414,127,702,189,8135,1699,1098,195,248,32
60,KECAMATAN,TAMBAKSARI,1247,685,586,283,9166,5933,9536,3845,...,521,167,971,289,7496,1670,546,112,40,17
69,KECAMATAN,SIMOKERTO,405,567,419,190,6254,3705,3942,1720,...,72,16,210,67,1834,448,108,27,4,0
75,KECAMATAN,PABEAN CANTIAN,239,155,286,125,4147,2840,2930,1318,...,88,24,284,89,1838,445,110,29,5,0
80,KECAMATAN,BUBUTAN,197,137,307,156,4193,2943,3718,1628,...,120,41,451,130,2764,688,182,47,10,2
86,KECAMATAN,TANDES,217,117,229,108,2721,1855,3008,1355,...,212,47,629,163,4144,823,262,63,5,0
93,KECAMATAN,KREMBANGAN,808,407,422,121,6847,4265,4890,1710,...,280,96,241,49,2714,584,222,38,8,0
99,KECAMATAN,SEMAMPIR,971,1004,1179,360,16246,7746,8063,2476,...,183,47,323,53,2089,466,145,19,7,0
105,KECAMATAN,KENJERAN,1171,451,1103,245,13916,5454,7725,1939,...,285,76,334,68,2897,424,177,40,11,1
110,KECAMATAN,LAKARSANTRI,325,194,205,80,2995,1429,2207,466,...,132,45,292,69,3024,507,233,41,21,1
117,KECAMATAN,BENOWO,105,85,153,70,3088,1700,3083,869,...,89,14,345,71,2314,313,147,22,10,2
122,KECAMATAN,WIYUNG,124,107,184,67,2294,1334,2200,694,...,196,43,537,124,4896,811,507,73,30,3
127,KECAMATAN,DUKUH PAKIS,108,72,146,90,1676,1188,1879,677,...,178,32,365,138,3214,682,298,47,20,4
132,KECAMATAN,GAYUNGAN,54,40,83,61,731,598,870,431,...,151,62,337,114,3591,733,529,89,43,7
137,KECAMATAN,JAMBANGAN,40,33,84,54,1197,834,1322,558,...,189,51,491,127,3820,647,477,80,34,2
142,KECAMATAN,TENGGILIS MEJOYO,58,62,160,98,1390,957,1888,722,...,148,64,378,141,3631,780,380,84,33,7
147,KECAMATAN,GUNUNG ANYAR,66,38,136,71,1264,871,1715,662,...,231,73,554,153,5197,869,531,76,59,14
152,KECAMATAN,MULYOREJO,236,138,181,90,2517,1558,2504,1106,...,235,87,477,139,6585,1383,684,133,80,12
159,KECAMATAN,SUKOMANUNGGAL,286,156,341,196,3748,2260,3698,1367,...,201,70,423,115,4133,825,268,41,18,3
166,KECAMATAN,ASEM ROWO,416,144,350,85,3921,1532,2169,551,...,59,11,83,14,729,124,67,13,2,0
170,KECAMATAN,BULAK,198,112,130,50,2572,1327,1967,553,...,91,24,221,44,1419,282,153,21,11,1
175,KECAMATAN,PAKAL,116,93,148,66,2278,1226,2366,709,...,121,16,367,80,2684,350,180,27,9,3
180,KECAMATAN,SAMBIKEREP,152,138,147,51,2785,1319,2345,715,...,140,41,431,105,3503,623,292,41,15,0

In [78]:
#SUM UNDER SMA
kolom_p = df1.columns[df1.columns.str.endswith('_P')]
under_sma = ['TIDAK/BELUM SEKOLAH_P', 'BELUM TAMAT SD/SEDERAJAT_P', 'TAMAT SD/SEDERAJAT_P', 'SLTP/SEDERAJAT_P']
# Gabungkan berdasarkan kecamatan/kelurahan
df_concat = df1.merge(
    df2,
    on='WILAYAH',
    suffixes=('_df1', '_df2')
)

# Jumlahkan masing-masing kolom
for col in under_sma:
    df_concat[col] = df_concat[f'{col}_df1'] + df_concat[f'{col}_df2']

# Ambil hanya kolom WILAYAH dan hasil jumlah under SMA


df_concat['KECAMATAN/KELURAHAN_df1']

0      JUMLAH TOTAL
1         KECAMATAN
2         KECAMATAN
3         KELURAHAN
4         KELURAHAN
           ...
230       KELURAHAN
231       KELURAHAN
232       KELURAHAN
233       KELURAHAN
234       KELURAHAN
Name: KECAMATAN/KELURAHAN_df1, Length: 235, dtype: str

In [71]:
df_concat

,KECAMATAN/KELURAHAN_df1,WILAYAH,TIDAK/BELUM SEKOLAH_L_df1,TIDAK/BELUM SEKOLAH_P_df1,BELUM TAMAT SD/SEDERAJAT_L_df1,BELUM TAMAT SD/SEDERAJAT_P_df1,TAMAT SD/SEDERAJAT_L_df1,TAMAT SD/SEDERAJAT_P_df1,SLTP/SEDERAJAT_L_df1,SLTP/SEDERAJAT_P_df1,...,DIPLOMA IV/STRATA I_L_df2,DIPLOMA IV/STRATA I_P_df2,STRATA II_L_df2,STRATA II_P_df2,STRATA III_L_df2,STRATA III_P_df2,TIDAK/BELUM SEKOLAH_P,BELUM TAMAT SD/SEDERAJAT_P,TAMAT SD/SEDERAJAT_P,SLTP/SEDERAJAT_P
0,JUMLAH TOTAL,KOTA SURABAYA,10071,6655,9142,3908,125485,74621,106253,41576,...,145311,158264,12277,10051,1147,651,300353,121926,314353,212892
1,KECAMATAN,KARANG PILANG,103,79,142,132,1802,1339,2274,854,...,4556,4973,368,307,28,18,7319,2293,5708,4673
2,KECAMATAN,KARANG PILANG,103,79,142,132,1802,1339,2274,854,...,236,334,12,13,0,0,832,436,1921,1305
3,KELURAHAN,KARANG PILANG,8,13,16,14,242,204,297,103,...,4556,4973,368,307,28,18,7253,2175,4573,3922
4,KELURAHAN,KARANG PILANG,8,13,16,14,242,204,297,103,...,236,334,12,13,0,0,766,318,786,554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,KELURAHAN,SAMBIKEREP,54,78,35,12,867,366,683,202,...,3994,4236,312,220,16,6,6131,2747,5519,4282
231,KELURAHAN,SAMBIKEREP,54,78,35,12,867,366,683,202,...,1433,1573,107,70,8,3,1817,962,2018,1464
232,KELURAHAN,MADE,21,23,19,14,602,231,402,74,...,500,549,39,30,3,1,844,410,1152,717
233,KELURAHAN,BERINGIN,11,3,16,3,288,168,278,79,...,181,193,14,10,0,1,509,304,764,502
234,KELURAHAN,LONTAR,66,34,77,22,1028,554,982,360,...,1880,1921,152,110,5,1,3021,1110,2538,2112

In [69]:
df_concat['WILAYAH'].value_counts()

WILAYAH
KARANG PILANG    4
WONOREJO         4
WONOKROMO        4
TEGALSARI        4
SAWAHAN          4
                ..
BABAT JERAWAT    1
SUMBER REJO      1
MADE             1
BERINGIN         1
LONTAR           1
Name: count, Length: 160, dtype: int64

In [ ]:
total_penduduk_p = 1516783
d